# Site settings
title: Divyang Mittal
email: divyangmittal44@gmail.com
description: Academic webpage of Divyang Mittal
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Divyang Mittal<br/>
    Software Engineer<br/>
    Appdynamics

# location: >
#   <a href="http://www.mce.caltech.edu/about/gates_thomas" target="_blank">Gates-Thomas Laboratory</a><br/>
#   California Institute of Technology <br/>
#   1200 E California Blvd<br/>
#   Pasadena, CA 91125, MC104-44

contact: >
    <a href="mailto:divyangmittal44@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Divyang via email</a> <br/>
    <a href="https://github.com/divyang-mittal"><i class="fa fa-github fa-1x"></i></a> <a href="https://www.linkedin.com/in/divyang-mittal-95a334170/"><i class="fa fa-linkedin fa-1x"></i></a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: research
  - name: software
# - name: team
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Mittal
  first_name: [Divyang]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
